[mod] 重新修改文档
longbridgeapp/openapi-website pull request #50
Opened 2022-04-28 15:01 UTC by sky-lft

@huacnlee 更新了代码下重新提交

2022-04-28 16:03 UTC, huacnlee commented
![image](https://user-images.githubusercontent.com/5518/165795464-15886a87-c190-4670-b676-da00bbf7e6e1.png)

2022-04-29 00:52 UTC, sky-lft commented
@huacnlee 我之前理解错了，以为是你这边要合并冲突的，我已经解决冲突了

2022-04-29 01:28 UTC, huacnlee requested changes

2022-04-29 01:28 UTC, huacnlee commented on swagger-docs/trade/asset/stock.yml
> +            auth = Auth("${API_KEY}", "${API_KEY_SECRET}", "${ACCESS_TOKEN}")
Same

2022-04-29 01:38 UTC, sky-lft commented
@huacnlee 已修改

2022-04-29 02:10 UTC, merged